import fs from 'fs';
import matter from 'gray-matter';
import { Heading, Link, Stack } from '@chakra-ui/react';
import NextLink from 'next/link';
import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';

import { getParsedDate } from '../../utils';

import { Post } from '../../types';

export const getStaticProps: GetStaticProps = async context => {
  // get list of files from the posts folder
  const files = fs.readdirSync('src/posts');

  // get frontmatter & slug from each post
  const posts = files.map(fileName => {
    const slug = fileName.replace('.md', '');
    const readFile = fs.readFileSync(`src/posts/${fileName}`, 'utf-8');
    const { data: frontmatter } = matter(readFile);

    return {
      slug,
      frontmatter
    };
  });

  // return the pages static props
  return {
    props: {
      posts
    }
  };
};

interface Props {
  posts: Post[];
}

const Blog: NextPage<Props> = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Cryptography Research | Ethereum Foundation</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* TODO: add another blog entry https://cryptography-website.netlify.app/blog/extreme-neon-what-is-this-trend-about */}
      <main>
        <Heading as='h1' mb={10}>
          Blog
        </Heading>

        <Stack>
          {posts.map(post => {
            //extract slug and frontmatter
            const { slug, frontmatter } = post;
            //extract frontmatter properties
            const { title, author, date } = frontmatter;
            const parsedDate = getParsedDate(date);

            //JSX for individual blog listing
            return (
              <article key={title}>
                <Heading as='h3' size='xs' fontWeight={400} mb={1}>
                  {parsedDate}
                </Heading>

                <NextLink href={`blog/${slug}`} passHref>
                  <Link
                    href={`blog/${slug}`}
                    color='brand.lightblue'
                    _hover={{ color: 'brand.orange', textDecoration: 'underline' }}
                  >
                    <Heading as='h1' mb={4} size='md' fontWeight={500}>
                      {title}
                    </Heading>
                  </Link>
                </NextLink>
              </article>
            );
          })}
        </Stack>
      </main>
    </>
  );
};

export default Blog;
