import { Heading, Link, Stack, Text } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';

const Bounties: NextPage = () => {
  return (
    <>
      <Head>
        <title>Cryptography Research | Ethereum Foundation</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Heading as='h1' mb={10}>
          Bounties
        </Heading>

        <Text mb={4}>Here&apos;s our bounties page!</Text>

        <Text mb={12}>Do want subpages within here? Or is one long page all we need?</Text>

        {/* TODO: links color update hover */}
        <Text mb={4}>
          To improve the cryptanalysis of new RSA assumptions needed for Verifiable Delay Functions
          (VDFs), the Ethereum Foundation announced the following bounties at Real World Crypto
          2020.{' '}
          <Link href='https://rsa.cash/bounties' color='blue.400'>
            https://rsa.cash/bounties
          </Link>
        </Text>

        <Text>
          Help us understand the security of new hash functions better. The Ethereum Foundation
          announced the following bounties in November 2021.{' '}
          <Link href='https://www.zkhashbounties.info/' color='blue.400'>
            https://www.zkhashbounties.info/
          </Link>
        </Text>
      </main>
    </>
  );
};

export default Bounties;
