import { Heading, Stack, Text } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';

const Events: NextPage = () => {
  return (
    <>
      <Head>
        <title>Cryptography Research | Ethereum Foundation</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Heading as='h1' mb={10}>
          Events
        </Heading>

        <Text>A list of events we help organize...</Text>
      </main>
    </>
  );
};

export default Events;
