import { Heading, Link, Stack, Text } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';

const Team: NextPage = () => {
  return (
    <>
      <Head>
        <title>Cryptography Research | Ethereum Foundation</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Heading as='h1' mb={10}>
          Team
        </Heading>

        <Text mb={12}>
          Meet our team of world leading cryptography researchers. It goes without saying that we
          are all interested in cryptography and blockchains. We also have more specific interests
          ranging from cryptanalysis to zero-knowledge proofs to post-quantum cryptography.
        </Text>

        <Stack spacing={9}>
          <Stack>
            <Text>
              <strong>Justin Drake.</strong> MEV, secret leader election, VDFs, zkEVM, sharding,
              proof-of-custody.
            </Text>

            <Text lineHeight='10px'>
              <Link
                href='https://twitter.com/drakefjustin'
                color='#14add2'
                _hover={{ color: '#f38b75', textDecoration: 'underline' }}
                isExternal
              >
                twitter.com/drakefjustin
              </Link>
            </Text>
          </Stack>

          <Stack>
            <Text>
              <strong>Dankrad Feist.</strong> Vector commitments; Verkle trees; MPCs; and
              zero-knowledge proofs.
            </Text>

            <Text lineHeight='10px'>
              <Link
                href='https://dankradfeist.de/about/'
                color='#14add2'
                _hover={{ color: '#f38b75', textDecoration: 'underline' }}
                isExternal
              >
                dankradfeist.de/about
              </Link>
            </Text>
          </Stack>

          <Stack>
            <Text>
              <strong>Gottfried Herold.</strong> Public key cryptanalysis.
            </Text>

            <Text lineHeight='10px'>
              <Link
                href='https://dblp.org/pid/47/11389.html'
                color='#14add2'
                _hover={{ color: '#f38b75', textDecoration: 'underline' }}
                isExternal
              >
                dblp.org/pid/47/11389.html
              </Link>
            </Text>
          </Stack>

          <Stack>
            <Text>
              <strong>George Kadianakis.</strong> Elliptic curves; zero-knowledge proofs; and
              protocol implementations.
            </Text>

            <Text lineHeight='10px'>
              <Link
                href='https://github.com/asn-d6'
                color='#14add2'
                _hover={{ color: '#f38b75', textDecoration: 'underline' }}
                isExternal
              >
                github.com/asn-d6
              </Link>
            </Text>
          </Stack>

          <Stack>
            <Text>
              <strong>Dmitry Khovratovich.</strong> Hash function design; cryptanalysis; SNARK
              friendly primitives; universal composibility.
            </Text>

            <Text lineHeight='10px'>
              <Link
                href='https://en.wikipedia.org/wiki/Dmitry_Khovratovich'
                color='#14add2'
                _hover={{ color: '#f38b75', textDecoration: 'underline' }}
                isExternal
              >
                en.wikipedia.org/wiki/Dmitry_Khovratovich
              </Link>
            </Text>
          </Stack>

          <Stack>
            <Text>
              <strong>Mary Maller.</strong> Zero-knowledge proofs; distributed key generation; and
              setup ceremonies.
            </Text>

            <Text lineHeight='10px'>
              <Link
                href='https://www.marymaller.com/'
                color='#14add2'
                _hover={{ color: '#f38b75', textDecoration: 'underline' }}
                isExternal
              >
                marymaller.com
              </Link>
            </Text>
          </Stack>

          <Stack>
            <Text>
              <strong>Mark Simkin.</strong> Cryptographic protocols and primitives, algorithms and
              data structures.
            </Text>

            <Text lineHeight='10px'>
              <Link
                href='https://msimkin.github.io/'
                color='#14add2'
                _hover={{ color: '#f38b75', textDecoration: 'underline' }}
                isExternal
              >
                msimkin.github.io
              </Link>
            </Text>
          </Stack>

          <Stack>
            <Text>
              <strong>Antonio Sanso.</strong> Isogenies; elliptic curves; public key cryptography;
              cryptanalysis.
            </Text>

            <Text lineHeight='10px'>
              <Link
                href='https://www.nds.ruhr-uni-bochum.de/chair/people/asanso/'
                color='#14add2'
                _hover={{ color: '#f38b75', textDecoration: 'underline' }}
                isExternal
              >
                nds.ruhr-uni-bochum.de/chair/people/asanso
              </Link>
            </Text>
          </Stack>

          <Stack>
            <Text>
              <strong>Zhenfei Zhang.</strong> Lattice based cryptography; zero-knowledge proofs;
              cryptographic implementations.
            </Text>

            <Text lineHeight='10px'>
              <Link
                href='https://zhenfeizhang.github.io/material/aboutme/'
                color='#14add2'
                _hover={{ color: '#f38b75', textDecoration: 'underline' }}
                isExternal
              >
                zhenfeizhang.github.io/material/aboutme
              </Link>
            </Text>
          </Stack>
        </Stack>
      </main>
    </>
  );
};

export default Team;
